# Generated by Django 6.0.5 on 2026-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Office', 'Office')], max_length=50)),
                ('listing_type', models.CharField(choices=[('For Sale', 'For Sale'), ('Monthly Rent', 'Monthly Rent'), ('Daily Rent', 'Daily Rent')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('size', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('elevator', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('rooms', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='properties/')),
            ],
        ),
    ]
