# Generated by Django 6.0.5 on 2026-05-23 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),

        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to='properties.property'
            ),
        ),

        migrations.RemoveField(
            model_name='review',
            name='name',
        ),

        migrations.AlterModelOptions(
            name='property',
            options={
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Properties'
            },
        ),

        migrations.AlterModelOptions(
            name='review',
            options={
                'ordering': ['-created_at']
            },
        ),
    ]