# Generated by Django 6.0.5 on 2026-05-24 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_contactmessage_options_propertyinquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='propertyinquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Property Inquiries'},
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='message',
            field=models.TextField(default='Example message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
            preserve_default=False,
        ),
    ]
