# Generated by Django 6.0.5 on 2026-05-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_favorites_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Sold', 'Sold'), ('Pending', 'Pending')], default='Available', max_length=50),
        ),
    ]
